
version: "3.9"
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"

  sshhost:
    image: linuxserver/openssh-server
    environment:
      PASSWORD_ACCESS: "true"
      USER_NAME: devops
      USER_PASSWORD: devops
    ports:
      - "2222:2222"
